#pragma once

#include <d3d9types.h>

typedef void (*FUNC)();

enum HWCAMERATYPE
{
	HWCT_FREE = 0,
	HWCT_RECT = 1,
	HWCT_MODELVIEW = 2,
};

enum HWTEXTURETYPE
{
	HWTEX_2D = 0,
	HWTEX_CUBE = 1,
//	HWTEX_3D = 2,
};

#define HWBU_STATIC 0;
#define HWBU_WRITEONLY D3DUSAGE_WRITEONLY;
#define HWBU_DYNAMIC D3DUSAGE_DYNAMIC;
#define HWBU_STATIC_WRITE_ONLY 0 | D3DUSAGE_WRITEONLY;
#define HWBU_DYNAMIC_WRITE_ONLY 0 | D3DUSAGE_DYNAMIC;

enum HWANIMRENDER
{
	HWAR_SOFTWARE = 0,
	HWAR_HARDWARE = 1,
};

enum HWANIMATIONTYPE
{
	HWAT_NONE = 0,
	HWAT_SKELET = 1,
};

enum HWANIMATIONMODE
{
	HWAM_NONE = 0,
	HWAM_PLAYONCE = 1,
};
